name: API Tests

on:
  push:
    branches: ["main"]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Lancer la collection Postman
        run: |
          npx postman-cli collection run "collections/Reqres Tests.postman_collection.json"
